language: node_js
node_js:
  "lts/*"
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  name: Publishment Bot
  on:
    branch: gh-pages
  local_dir: _book
